<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ZConectInputHelper</AssemblyName>
    <RootNamespace>ZConectInputHelper</RootNamespace>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWindowsForms>false</UseWindowsForms>
    <UseWPF>false</UseWPF>
  </PropertyGroup>
</Project>
