using System.IO;
using System.Text.Json;
using UiApp.Models;

namespace UiApp.Services;

/// <summary>Хранит адресную книгу контактов в %AppData%\ZConect\address-book.json. Данные чувствительны — хранятся локально.</summary>
public sealed class AddressBookService
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    public string AddressBookPath { get; }

    public AddressBookService()
    {
        var dir = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
            "ZConect");
        Directory.CreateDirectory(dir);
        AddressBookPath = Path.Combine(dir, "address-book.json");
    }

    /// <summary>Test-only constructor: uses a custom file path (no auto-directory creation).</summary>
    internal AddressBookService(string customPath)
    {
        AddressBookPath = customPath;
    }

    public List<Contact> Load()
    {
        if (!File.Exists(AddressBookPath))
        {
            return new List<Contact>();
        }

        try
        {
            var raw = File.ReadAllText(AddressBookPath);
            var list = JsonSerializer.Deserialize<List<Contact>>(raw, JsonOptions);
            if (list is not null)
            {
                // DPAPI decrypt sensitive fields per-contact. Plaintext fields (legacy)
                // пропускаются без изменений — migration "lazy" (encrypt on next Save).
                foreach (var c in list) DecryptContact(c);
            }
            return list ?? new List<Contact>();
        }
        catch
        {
            return new List<Contact>();
        }
    }

    public void Save(List<Contact> contacts)
    {
        // Work on deep-copy чтобы in-memory объекты остались plaintext для UI binding'а.
        var clones = contacts.Select(CloneAndEncrypt).ToList();
        var raw = JsonSerializer.Serialize(clones, JsonOptions);
        File.WriteAllText(AddressBookPath, raw);
    }

    private static Contact CloneAndEncrypt(Contact c)
    {
        var clone = new Contact
        {
            Id = c.Id,
            Name = c.Name,
            ServerApiBaseUrl = c.ServerApiBaseUrl,
            LoginCode = c.LoginCode,
            PassCode = c.PassCode,
            SavedUnattendedPassword = c.SavedUnattendedPassword,
            LastConnectedUtc = c.LastConnectedUtc,
            IsAutoGenerated = c.IsAutoGenerated,
        };
        EncryptContact(clone);
        return clone;
    }

    private static void EncryptContact(Contact c)
    {
        // SavedUnattendedPassword — единственное чувствительное поле сейчас.
        // Login/Pass codes session-bound (короткий TTL) — не encrypt'им, historically plaintext.
        if (!string.IsNullOrEmpty(c.SavedUnattendedPassword) && !DpapiHelper.IsEncrypted(c.SavedUnattendedPassword))
            c.SavedUnattendedPassword = DpapiHelper.Encrypt(c.SavedUnattendedPassword);
    }

    private static void DecryptContact(Contact c)
    {
        if (DpapiHelper.IsEncrypted(c.SavedUnattendedPassword))
            c.SavedUnattendedPassword = DpapiHelper.Decrypt(c.SavedUnattendedPassword);
    }
}
