using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Text.Json.Serialization;
using UiApp.Properties;

namespace UiApp.Models;

/// <summary>Контакт адресной книги для подключения без ввода кодов (режим «только передача файлов» или удалённый стол).</summary>
public sealed class Contact : INotifyPropertyChanged
{
    private string _name = string.Empty;
    private string _serverApiBaseUrl = string.Empty;
    private string _loginCode = string.Empty;
    private string _passCode = string.Empty;

    public string Id { get; set; } = Guid.NewGuid().ToString("N");

    public string Name
    {
        get => _name;
        set { _name = value; OnPropertyChanged(); OnPropertyChanged(nameof(FirstLetter)); }
    }

    private bool _isAutoGenerated;
    /// <summary>True если контакт создан автоматически после ad-hoc connect (имя вида
    /// «Сеанс 5678»). Пользователь не дал ему осмысленное имя. Используется для:
    ///  - показа иконки «?» в Recent card вместо первой буквы;
    ///  - подсветки prompt'а переименования при следующем connect;
    ///  - «Очистить Recent» удаляет только такие контакты (named — оставляет в AB).
    /// Set to false когда user переименовывает через PromptDialog или Edit в Address Book.</summary>
    public bool IsAutoGenerated
    {
        get => _isAutoGenerated;
        set { _isAutoGenerated = value; OnPropertyChanged(); OnPropertyChanged(nameof(FirstLetter)); }
    }

    /// <summary>Символ для аватара в Recent row / Address Book.
    ///   - IsAutoGenerated (ephemeral) → «?»
    ///   - Иначе → первая буква имени в верхнем регистре
    /// (Emoji в имени поддерживались в коротком эксперименте, но WPF TextBlock не
    /// рендерит color fonts — был только monochrome outline. Откатил до букв.)</summary>
    public string FirstLetter
    {
        get
        {
            if (_isAutoGenerated) return "?";
            if (string.IsNullOrWhiteSpace(_name)) return "?";
            return _name.Trim().Substring(0, 1).ToUpperInvariant();
        }
    }

    /// <summary>Базовый URL API сервера (например https://example.com или http://192.168.1.10:8080).</summary>
    public string ServerApiBaseUrl
    {
        get => _serverApiBaseUrl;
        set { _serverApiBaseUrl = value; OnPropertyChanged(); }
    }

    public string LoginCode
    {
        get => _loginCode;
        set { _loginCode = value; OnPropertyChanged(); }
    }

    public string PassCode
    {
        get => _passCode;
        set { _passCode = value; OnPropertyChanged(); }
    }

    private string _savedUnattendedPassword = string.Empty;
    /// <summary>
    /// Сохранённый local password для unattended-подключения к этому host'у. Plaintext в памяти,
    /// DPAPI-encrypted при сохранении через AddressBookService. Пустой если user не чекнул
    /// «Запомнить пароль» в UnattendedPasswordDialog или очистил вручную.
    /// </summary>
    public string SavedUnattendedPassword
    {
        get => _savedUnattendedPassword;
        set { _savedUnattendedPassword = value ?? string.Empty; OnPropertyChanged(); }
    }

    private DateTime? _lastConnectedUtc;
    /// <summary>UTC timestamp последнего успешного подключения к этому контакту. Null если
    /// никогда не подключались (например, только добавили в адресную книгу). Используется для
    /// секции «Недавно подключённые» на вкладке «Создать сессию» — показывает top-N контактов
    /// отсортированных по убыванию этого времени. Nullable чтобы не ломать существующие
    /// address-book.json без этого поля (JSON deserialize вернёт null).</summary>
    public DateTime? LastConnectedUtc
    {
        get => _lastConnectedUtc;
        set { _lastConnectedUtc = value; OnPropertyChanged(); OnPropertyChanged(nameof(LastConnectedDisplay)); }
    }

    /// <summary>Человекочитаемое представление LastConnectedUtc для UI («2 мин назад»,
    /// «вчера», «2 дня назад», «3 недели назад»). Вычисляется по-русски, обновляется
    /// когда меняется LastConnectedUtc.</summary>
    public string LastConnectedDisplay
    {
        get
        {
            if (!_lastConnectedUtc.HasValue) return string.Empty;
            var delta = DateTime.UtcNow - _lastConnectedUtc.Value;
            if (delta.TotalSeconds < 60) return Strings.Time_JustNow;
            if (delta.TotalMinutes < 60) return string.Format(Strings.Time_MinutesAgo_Format, (int)delta.TotalMinutes);
            if (delta.TotalHours < 24)   return string.Format(Strings.Time_HoursAgo_Format, (int)delta.TotalHours);
            if (delta.TotalDays < 2)     return Strings.Time_Yesterday;
            if (delta.TotalDays < 7)     return string.Format(Strings.Time_DaysAgo_Format, (int)delta.TotalDays);
            if (delta.TotalDays < 30)    return string.Format(Strings.Time_WeeksAgo_Format, (int)(delta.TotalDays / 7));
            return string.Format(Strings.Time_MonthsAgo_Format, (int)(delta.TotalDays / 30));
        }
    }

    // Live presence — виден (🟢/🔴/⚪) dot на avatar. Обновляется PresenceService'ом
    // каждые 30 сек. Не хранится в address-book.json — runtime only.
    //
    // [JsonIgnore] на Presence+PresenceBrush+PresenceTooltip — bug audit 2026-04-24:
    // без этого AddressBookService.Save() шёл в stack overflow при serialization
    // PresenceBrush (WPF SolidColorBrush рекурсивно walks Dispatcher / visual tree).
    // Все 3 — runtime-only fields, не должны persist'иться в JSON.
    private Services.PresenceState _presence = Services.PresenceState.Unknown;
    [JsonIgnore]
    public Services.PresenceState Presence
    {
        get => _presence;
        set
        {
            if (_presence == value) return;
            _presence = value;
            OnPropertyChanged();
            OnPropertyChanged(nameof(PresenceBrush));
            OnPropertyChanged(nameof(PresenceTooltip));
        }
    }

    /// <summary>#22C55E зелёный / #6B7280 серый / #9CA3AF светло-серый</summary>
    [JsonIgnore]
    public System.Windows.Media.Brush PresenceBrush => _presence switch
    {
        Services.PresenceState.Online  => System.Windows.Media.Brushes.LimeGreen,
        Services.PresenceState.Offline => System.Windows.Media.Brushes.DimGray,
        _                              => System.Windows.Media.Brushes.LightGray,
    };

    [JsonIgnore]
    public string PresenceTooltip => _presence switch
    {
        Services.PresenceState.Online  => Strings.Presence_Online_Tooltip,
        Services.PresenceState.Offline => Strings.Presence_Offline_Tooltip,
        _                              => Strings.Presence_Unknown_Tooltip,
    };

    public event PropertyChangedEventHandler? PropertyChanged;
    private void OnPropertyChanged([CallerMemberName] string? prop = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(prop));
}
