<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FileTransfer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WebRtcTransport\WebRtcTransport.csproj" />
  </ItemGroup>
</Project>
